
add_newline = false
format=""" $username$hostname$directory$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$golang$haskell$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$buf$nix_shell$character"""

[character]
success_symbol = "[â¯](bold green)"

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo=false
read_only="ğŸ”’"
read_only_style="red"

[hostname]
ssh_only = true
format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = false

[python]
symbol = "îœ¼ "

[nodejs]
symbol = " "
detect_extensions=["js", "mjs", "cjs", "ts", "mts", "cts","jsx"]


[rust]
symbol = "î¨ "